# Generated by Django 5.2.10 on 2026-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(error_messages={'unique': 'Employee ID already exists.'}, max_length=20, unique=True),
        ),
    ]
